server: 
  port: 58888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///cyou?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:
  mongodb:
    host: 127.0.0.1
    database: spitdb
  jpa: 
    database: MySQL
    show-sql: true

#  rabbitmq:
#    host: 127.0.0.1
redis:
  host: 127.0.0.1
jwt:
  config:
    key: www.ccstay.com.by.cc
    ttl: 3600000
aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code: SMS_184205569
    sign_name: CC


